# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_bbbcp_gibbs <- function(x, n, prior, control) {
    .Call('binomialbcp_rcpp_bbbcp_gibbs', PACKAGE = 'binomialbcp', x, n, prior, control)
}

